apiVersion: v1
kind: Service
metadata:
  name: observability-app-svc
  namespace: default
spec:
  selector:
    app: observability-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort